services:

  bot:
    build:
      context: .
      dockerfile: Dockerfile

    env_file:
      - .env
    volumes:
      - .:/app
    networks:
      - pudimatrix-default
    depends_on:
      - database

  database:
    image: postgres:15.8-alpine
    environment:
      POSTGRES_DB: pudimatrix
      POSTGRES_USER: pudimatrix
      POSTGRES_PASSWORD: test
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - database-data:/var/lib/postgresql/data
    networks:
      - pudimatrix-default
    

networks:
  pudimatrix-default:
    driver: bridge

volumes:
  database-data:
